
LETRA_1 EQU 041h ; DEFINE 1a. COLUNA COM A LETRA A
LETRA_8 EQU 048h ; DEFINE ULTIMA COLUNA COM LETRA H
NUMERO_1 EQU 31h
NUMERO_8 EQU 38h

org 100h


MOV SI, offset JOGADA ;MOVE O VETOR DE JOGADAS PARA A MEMORIA

     
;*******************INICIO**********************************


AGUARDA_LETRA:
    
    MOV BL, LETRA_1        ;REGISTRADOR AUXILIAR
    MOV BH, LETRA_8 
    MOV AX,0               ;CHAMA O SERVICO 0
    INT 16h                ;DO INT 16h (FUNCAO QUE ESPERA A TECLA)   
           
TESTA_LETRA:        
  
    CMP AL, BL             ; COMPARA SE VALOR DIGITADA EH IGUAL A U
    JE SALVA_LETRA         ; SE SIM IRA SALVAR A LETRA NO VETOR DE JOGADAS          
  
    MOV CL,BL              ; UTILIZA UM CONTADOR AUXILIAR PARA COMPARAR SE VALOR DIGITADO EH MAIOR QUE "H" OU MENOR QUE "A"
    SUB CL,BH
    JNC AGUARDA_LETRA      ; VALOR DEVE APRESENTAR CARRY, CASO CONTRARIO VALOR NAO EH ACEITO
  
    INC BL                 ; INCREMENTA CONTADOR
    JMP TESTA_LETRA        ; RECURSAO       

SALVA_LETRA:                 
  
    MOV [SI],AL            ; SALVA VALOR DIGITADO NA MEMORIA
    INC SI

               
AGUARDA_NUMERO:
  
    MOV BL, NUMERO_1        ;REGISTRADOR AUXILIAR COMO CONTADOR
    MOV BH, NUMERO_8 
    MOV AX,0               ;CHAMA O SERVICO 0
    INT 16h                ;DO INT 16h (FUNCAO QUE ESPERA A TECLA)   

           
TESTA_NUMERO:        
  
    CMP AL, BL             ; COMPARA SE VALOR DIGITADA EH IGUAL A U
    JE SALVA_NUMERO         ; SE SIM IRA SALVAR A LETRA NO VETOR DE JOGADAS          
  
    MOV CL,BL              ; UTILIZA UM CONTADOR AUXILIAR PARA COMPARAR SE VALOR DIGITADO EH MAIOR QUE "H" OU MENOR QUE "A"
    SUB CL,BH
    JNC AGUARDA_NUMERO      ; VALOR DEVE APRESENTAR CARRY, CASO CONTRARIO VALOR NAO EH ACEITO
  
    INC BL                 ; INCREMENTA CONTADOR
    JMP TESTA_NUMERO        ; RECURSAO       

SALVA_NUMERO:                 
  
    MOV [SI],AL            ; SALVA VALOR DIGITADO NA MEMORIA
    INC SI

;************************************************************


ESCREVE_TELA:
    
    MOV AX, 0B800h  
    MOV ES, AX
    MOV DI, 0000h
    MOV SI, offset JOGADA   ;REPOSICIONA VETOR DE JOGADAS NO INICIO

    
VOLTA:
    
    MOV AL,[SI]
    MOV ES:[DI], AL                ;; ESCREVE POSICAO DO VETOR NA TELA
    ;MOV ES:[DI+1], 10101110b      ;; ATRIBUTO
    INC DI               
    INC DI
    INC SI

    CMP AL,0
    JNZ VOLTA


ret

JOGADA:               ;VETOR ONDE SERA ESCRITO OS DADOS DO JOGO
    DB "0000000000000000",0

